[package]
name = "programming_language"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0
debug = "full"

[dependencies]
inkwell = { version = "0.7.1", features = ["llvm21-1"] }
clap = { version = "4.5.53", features = ["derive"]}
tempfile = "3.23.0"
